title: Dong Wang's Homepage
page-top-title: Dong Wang
top-section-bg-text: Computational Mineral Physics
home-subtitle: Dong Wang&ensp;|&ensp;王冬
copyright-text: '&copy; Dong Wang 2025-2026. All Rights Reserved.'
